Chats controller dto
beetroot-c-sharp-107/C_Sharp_107_Noslack pull request #5
Opened 2023-12-04 17:50 UTC by illia1304

2023-12-04 19:01 UTC, AlexSabaka requested changes
Please fix issues that I pointed out in the comments.

2023-12-04 19:01 UTC, AlexSabaka commented on backend/DTO/ChatControllerDTO/MessageDTO.cs
> +    public string SentDate {  get; set; }
It's better to use DateTime instead of string.

2023-12-06 17:50 UTC, AlexSabaka requested changes
Please 1. pull changes from main, 2. update missing code.

2023-12-11 17:40 UTC, AlexSabaka requested changes

2023-12-11 17:40 UTC, AlexSabaka commented on backend/Controllers/ChatsController.cs
> +        return Ok(_mapper.Map<Chat, GetChatDTO>(chat));
Should return a chatDTO variable

2023-12-11 17:40 UTC, AlexSabaka commented on backend/Controllers/ChatsController.cs
> +        int participantId = chat.UserId2 == currentUserId ? chat.UserId2 : chat.UserId1;
Should invert the ternary operator result – when currentUserId == UserId2, then participantId = UserId1, and vice versa

2023-12-11 17:57 UTC, Yurii-Shevchuk approved these changes
I believe in Oleksiy's judgement and therefore announce this review a decent merger into the main branch

2023-12-11 17:58 UTC, merged